package com.global.project.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@AllArgsConstructor
@NoArgsConstructor
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "UNCATEGORIZED ERROR"),
    INVALID_KEY(1001, "INVALID MESSAGE KEY"),

    USER_USERNAME_EXISTED(2002, "USER USERNAME ALREADY EXISTS"),
    USER_NOT_FOUND(2003, "USER NOT FOUND"),
    USER_CANT_CREATE_USER(2004, "USER CANT CREATE USER"),
    FIRSTNAME_OR_LASTNAME_IS_EMPTY(2008, "FIRSTNAME OR LASTNAME IS EMPTY"),
    FIRSTNAME_INVALID(2009, "First Name contains invalid characters. Only letters, spaces, hyphens, and apostrophes are allowed."),
    LASTNAME_INVALID(2010, "Last Name contains invalid characters. Only letters, spaces, hyphens, and apostrophes are allowed."),
    FIRSTNAME_TOO_LONG(2012, "First name is too long. Maximum length is 50 characters."),
    LASTNAME_TOO_LONG(2011, "Last name is too long. Maximum length is 50 characters."),
    USERNAME_IS_EMPTY(2013, "Username is empty."),
    USERNAME_INVALID(2014, "Username contains invalid characters. Only letters, numbers, periods, underscores, and hyphens are allowed."),
    ACCOUNT_EMAIL_EXISTED(2003, "ACCOUNT EMAIL EXISTS"),
    ACCOUNT_NOT_FOUND(2004, "ACCOUNT NOT FOUND"),
    PRIVATE_POST(2005, "PRIVATE POST"),
    USER_HAS_NO_PERMISSIONS(2006, "USER HAS NO PERMISSIONS"),
    YOUR_ACCOUNT_HAS_BEEN_BANNED_FROM_POSTING(2006, "YOUR ACCOUNT HAS BEEN BANNED FROM POSTING"),
    YOUR_ACCOUNT_HAS_BEEN_BANNED_FROM_COMMENTING(2006, "YOUR ACCOUNT HAS BEEN BANNED FROM COMMENTING"),

    INFO_NOT_FOUND(3000, "INFO NOT FOUND"),
    INVALID_STUDY(3001, "Study contains invalid characters. Only letters, numbers, and spaces are allowed."),
    INVALID_WORK_AT(3002, "WorkAt contains invalid characters. Only letters, numbers, and spaces are allowed."),
    INVALID_BIO(3003, "Bio contains invalid characters. Only letters, numbers, spaces, periods, commas, and exclamation marks are allowed."),
    INVALID_ADDRESS(3004, "Address contains invalid characters. Only letters, numbers, spaces, commas, periods, and hyphens are allowed."),
    INVALID_LIVE_AT(3005, "LiveAt contains invalid characters. Only letters, numbers, spaces, commas, periods, and hyphens are allowed."),
    INVALID_FROM_AT(3006, "FromAt contains invalid characters. Only letters, numbers, spaces, commas, periods, and hyphens are allowed."),
    INVALID_NICKNAME(3007, "Nickname contains invalid characters. Only letters, numbers, and spaces are allowed."),

    INVALID_MISSING_TOKEN(2001, "Invalid or missing Authorization token"),
    TOKEN_RESET_PASSWORD_INVALID(2005, "TOKEN RESET PASSWORD INVALID"),
    TOKEN_RESET_PASSWORD_EXPIRED(2006, "TOKEN RESET PASSWORD EXPIRED"),
    TOKEN_RESET_NOT_MATH(2007, "TOKEN RESET PASSWORD NOT MATCH"),

    POST_NOT_FOUND(4000, "POST NOT FOUND"),
    POST_HAS_BEEN_DELETED(4001, "POST HAS BEEN DELETED"),
    POST_HAS_BEEN_REPORTED(4002, "POST HAS BEEN REPORTED"),
    INVALID_POST_ID(4003, "INVALID POST ID"),
    INVALID_TYPE_ITEM(4004, "INVALID TYPE ITEM"),
    INVALID_TYPE_REACTION(4005, "INVALID TYPE REACTION"),
    INVALID_ITEM_ID(4006, "INVALID ITEM ID"),
    INVALID_TYPE_FEEDBACK(4007, "INVALID TYPE FEEDBACK"),
    COMMENT_NOT_FOUND(4000, "COMMENT NOT FOUND"),
    CANT_FIND_SAVED_POST(4000, "CANT FIND SAVED POST"),
    POST_HAS_BEEN_SAVE(4000, "POST HAS BEEN SAVE"),
    POST_HAS_BEEN_HIDDEN(4000, "POST HAS BEEN HIDDEN"),

    INVALID_CREDENTIAL(1002, "INVALID CREDENTIAL"),
    TOKEN_EXPIRED(1003, "TOKEN EXPIRED"),
    ACCOUNT_INVALID(1004, "ACCOUNT INVALID"),
    LOGIN_FAILED(1005, "LOGIN FAILED"),

    REFRESH_TOKEN_NOT_FOUND(1006, "REFRESH TOKEN NOT FOUND"),
    LOGOUT_FAILED(1007, "LOGOUT FAILED"),
    ERROR_(1009, "An error occurred while retrieving account details"),
    FILE_UPLOAD_FAILED(2000, "FILE UPLOAD FAILED"),

    HASTAG_CREATE_LIST_FAILED(2000, "ERROR WHEN INSERT LIST HASTAG TO DB"),

    TWEET_NOT_FOUND(2001, "TWEET NOT FOUND"),

    INVALID_TYPE_TIME(2000, "INVALID TYPE TIME"),

    INVALID_REPORT_STATUS(2000, "INVALID REPORT STATUS"),

    DOESNT_SUPPORT_DAILY_USER_STATISTICS(2001, "DOESNT SUPPORT DAILY USER STATISTICS"),

    IMAGE_CREATE_LIST_FAILD(2000, "ERROR WHEN INSERT LIST IMAGE TO DB"),
    IMAGE_SIZE_TOO_LARGE(2000, "IMAGE SIZE TOO LARGE"),
    IMAGE_NOT_EXACT_TYPE(2000, "IMAGE NOT EXACT TYPE"),
    POST_ID_TO_UPDATE_CANT_BE_NULL(2000, "POST ID TO UPDATE CANT BE NULL"),
    ROLE_NOT_FOUND(2001, "ROLE NOT FOUND"),

    TWEET_MENTOIN_CREATE_LIST_FAILED(2001, "ERROR WHEN INSERT LIST MENTION TO DB"),

    REGISTER_ACCOUNT_FAILED(2001, "REGISTER FAILED"),
    EMAIL_INCORRECT_FORMAT(2002, "EMAIL INCORRECT FORMAT"),
    FIRTNAME_CANT_BE_EMPTY(2003, "FIRT NAME CANT BE EMPTY"),
    LASTNAME_CANT_BE_EMPTY(2004, "LASTNAME CANT BE EMPTY"),
    PASSWORD_SIGNUP_TOO_SHORT(2003, "PASSWORD TOO SHORT"),

    GENDER_SIGNUP_INVALID(2004, "GENDER SIGNUP INVALID"),
    DOB_SIGNUP_INVALID(2004, "DOB SIGNUP INVALID"),
    EMAIL_SIGNIN_INVALID(2005, "EMAIL SIGNIN INVALID"),
    NEWPASSWORD_TOO_SHORT(2005, "NEW PASSWORD TOO SHORT"),
    NEWPASSWORD_CANT_SAME_OLD_PASSWORD(2005, "NEW PASSWORD CAN'T BE SAME OLD PASSWORD"),
    CANT_NOT_UPDATE_OTHER_PEOPLE_POST(2000, "CAN'T UPDATE OTHER POST"),

    UNSUPPORTED_FILE_TYPE(2000, "UNSUPPORTED FILE TYPE"),
    CANT_CREATE_POST(2000, "CANT NOT CREATE POST"),

    TAG_NOT_FOUND(2000, "TAG NOT FOUND"),
    CANT_NOT_TAG_YOURSELF(2000, "CAN'T NOT TAG YOURSELF"),

    TWEET_HASTAG_CREATE_LIST_FAILED(2000, "ERROR WHEN INSERT LIST TWEET HASTAG TO DB"),
    MEDIA_NOT_EXIST(2000, "MEDIA NOT EXIST"),
    VERIFY_CODE_EXPIRED(2000, "CODE IS EXPIRED TO VERIFY"),
    KEY_SEARCH_CANT_BE_NULL(2000, "KEY SEARCH CANT BE NULL"),
    FILE_NOT_FOUND(2000, "FILE IS NULL CAN'T BE TO SAVE"),

    NO_FRIEND_REQUEST_FOUND(2000, "NO FRIEND REQUEST FOUND"),
    CANT_SEND_FRIEND_REQUEST(2000, "CANT SEND FRIEND REQUEST"),
    NOT_FRIEND(2000, "IT'S NOT THAT FRIENDS CAN'T BE UNFRIENDED"),

    REASON_NOT_FOUND(2000, "REASON NOT FOUND"),
    CANT_FIND_REPORT_OBJECT(2000, "CANT FIND REPORT OBJECT"),

    CANT_BLOCK_YOURSELF(2000, "CAN'T BLOCK YOURSELF"),
    CANT_UNBLOCK_YOURSELF(2000, "CAN'T UNBLOCK YOURSELF"),
    USER_NOT_BLOCKED(2000, "USER NOT BLOCKED"),
    BLOCK_NOT_FOUND(2000, "BLOCK NOT FOUND"),
    PAGE_NUMBER_INVALID(2000, "PAGE NUMBER INVALID"),
    PAGE_SIZE_INVALID(2000, "PAGE SIZE INVALID"),
    USER_BLOCKED(2000, "USER BLOCKED"),
    ACCOUNT_NOT_ACTIVE(2000, "LOCKED ACCOUNT CANNOT LOG IN"),
    ID_SENDER_IN_NOTIFICATION_CANT_BE_NULL(2000, "SENDER ID CANNOT BE NULL"),
    TYPE_NOTIFICATION_INAVLID(2000, "TYPE NOTIFICATION INVALID"),
    NOTIFICATION_NOT_FOUND(2000, "NOTIFICATION NOT FOUND"),

    CONVERSATION_NOT_FOUND(2000, "CONVERSATION NOT FOUND"),
    PASSWORD_TOO_SHORT(2000, "PASSWORD TOO SHORT"),
    CURRENT_PASSWORD_NOT_EXACT(2000, "CURRENT PASSWORD NOT EXACT"),
    ACCESS_DENIED(2000, "ACCESS DENIED"),
    INVALID_RECIPIENT(2000, "INVALID RECIPIENT"),
    MESSAGE_NOT_FOUND(2000, "MESSAGE NOT FOUND"),
    PARTICIPANT_NOT_FOUND(2000, "PARTICIPANT NOT FOUND"),
    TYPE_MEDIA_INVALID(2000, "TYPE MEDIA INVALID"),
    INVALID_URL(2000, "INVALID TO URL"),
    NO_POSTS_TO_RESTORE(2000, "NO POSTS TO RESTORE"),
    ERROR_WHEN_DELETE_ATTRIBUTE_POST(2000, "ERROR WHEN DELETE ATTRIBUTE POST"),
    TEST_I18N_SERVICE(2000, "TEST I18N SERVICE"),
    GREETING(2000, "GREETING"),
    CANT_FIND_HIDDEN_POST(2000, "CANT FIND HIDDEN POST"),
    STARTDATE_CANT_AFTER_ENDdATE(2000, "START DATE CANT AFTER END DATE"),
    LANGUAGE_INVALID(2000, "LANGUAGE INVALID"),
    REPORT_NOT_FOUND(2000, "REPORT NOT FOUND"),
    NO_ROLE_ACCESS(2000, "NO ROLE ACCESS"),
    PRIVACY_NOT_EXIST(2000, "PRIVACY NOT EXIST"),
    STORY_CANT_BE_NULL(2000, "STORY CANT BE NULL"),
    STORY_NOT_FOUND(2000, "STORY NOT FOUND"),
    TOKEN_INVALID(2000, "TOKEN INVALID"),
    YOU_CANT_REPORT_YOUR_OWN_ACCOUNT(2000, "YOU_CANT_REPORT_YOUR_OWN_ACCOUNT"),
    YOU_CANT_REPORT_YOUR_OWN_POST(2000, "YOU_CANT_REPORT_YOUR_OWN_POST"),
    LASTNAME_TOO_SHORT(2000, "LASTNAME TOO SHORT"),
    FIRSTNAME_TOO_SHORT(2000, "FIRSTNAME TOO SHORT"),
    INVALID_CONVERSATION_ID(2000, "INVALID CONVERSATION ID");

    private int code;
    private String message;
}
